version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "yarn"
    directory: "/contracts"
    schedule:
      interval: "weekly" 