cacheFolder: .yarn/cache

enableGlobalCache: true

enableMirror: true

nodeLinker: node-modules

nmMode: hardlinks-local

enableScripts: true

enableStrictSsl: true

enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard

yarnPath: .yarn/releases/yarn-4.9.2.cjs
